networks:
  loki: {}
services:
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/no_folder/loki_syslog_aio_overview.json
    image: grafana/grafana:8.1.2
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: always
    volumes:
    - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    - /Users/enderx/syslog/grafana:/var/lib/grafana
  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:2.3.0
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: always
    volumes:
    - ./config/loki-config-filesystem.yml:/etc/loki/loki-config.yml:ro
    - ./config/rules:/etc/loki/rules:ro
    - /Users/enderx/syslog/loki:/tmp/loki/
  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:2.3.0
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: always
    volumes:
    - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      loki: null
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: always
    volumes:
    - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle"
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 9090
      target: 9090
    restart: always
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - /Users/enderx/syslog/prometheus:/prometheus
version: '3.3'
